version: '2'
services:
  php7:
    build: ./docker/php7
    ports:
      - "9000"
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    environment: 
      XDEBUG_CONFIG: remote_host=192.168.50.75 #Подставить свой удаленный IP
      PHP_IDE_CONFIG: "serverName=docker"
      DATABASE_NAME: testing
      DATABASE_USER: root
      DATABASE_PASSWORD: root